export const users = [
  { name: 'shohei (Shohei Saeki)', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'Naoto Sato', location_uuid: '', nickname: '', team: 'Backend2' },
  { name: 'Shingo Ichikawa', location_uuid: '', nickname: '', team: 'Backend2' },
  { name: 'wako', location_uuid: '', nickname: '', team: 'Backend2' },
  { name: 'Keisuke Nasu', location_uuid: '', nickname: '', team: 'CSTool PM' },
  { name: 'mkazutaka', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'Jason Lau', location_uuid: '', nickname: '', team: 'Backend2' },
  { name: 'Yuto Matsukubo', location_uuid: '', nickname: '', team: 'Backend2' },
  { name: 'gloria', location_uuid: '', nickname: '', team: 'AQA' },
  { name: 'osamu', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'sawachan', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'Daishu', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'yagihash', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'unryu-in', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'hikichin', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: 'xcezx', location_uuid: '', nickname: '', team: 'Defense Force' },
  { name: '', location_uuid: '', nickname: '', team: '' },
  { name: 'mtsuka', location_uuid: '', nickname: '', team: 'Microservice Platform' },
  { name: 'tomoyat1', location_uuid: '', nickname: '', team: 'Microservice Platform' },
  { name: 'nathan', location_uuid: '', nickname: '', team: 'Microservice Platform' },
  { name: 'dtan4', location_uuid: '', nickname: '' },
  { name: 'vishal', location_uuid: '', nickname: '' },
  { name: 'deeeet', location_uuid: '', nickname: '' },
  { name: 'babarot', location_uuid: '', nickname: '' },
  { name: 'spesnova', location_uuid: '', nickname: '' },
  { name: 'lainra', location_uuid: '', nickname: '' },
  { name: 'kakky', location_uuid: '', nickname: '' },
  { name: 'ichirin', location_uuid: '', nickname: '' },
  { name: 'xcezx', location_uuid: '', nickname: '' },
  { name: 'm-shibuya', location_uuid: '', nickname: '' },
  { name: 'ikarashi', location_uuid: '', nickname: '' },
  { name: 'k-oguma', location_uuid: '', nickname: '' },
  { name: 'kz', location_uuid: '', nickname: '' },
  { name: 'kazeburo', location_uuid: '', nickname: '' },
  { name: 'siroken3', location_uuid: '', nickname: '' },
  { name: 'bokko', location_uuid: '', nickname: '' },
  { name: 'catatsuy', location_uuid: '', nickname: '' },
  { name: 'mtokioka', location_uuid: '', nickname: '' },
  { name: 'shmorimo', location_uuid: '', nickname: '' },
  { name: 't-naritomi', location_uuid: '', nickname: '' },
  { name: 'kokukuma', location_uuid: '', nickname: '' },
  { name: 'morikuni', location_uuid: '', nickname: '' },
  { name: 'carlo', location_uuid: '', nickname: '' },
  { name: 'terry', location_uuid: '', nickname: '' },
  { name: 'stanaka', location_uuid: '', nickname: '' },
  { name: 'gilbite', location_uuid: '', nickname: '' },
  { name: 'codehex', location_uuid: '', nickname: '' },
  { name: 'takady', location_uuid: '', nickname: '' },
  { name: 'hunter', location_uuid: '', nickname: '' },
  { name: 'hidenorigoto', location_uuid: '', nickname: '' },
  { name: 'hachi', location_uuid: '', nickname: '' },
  { name: 'payao', location_uuid: '', nickname: '' },
  { name: 'sters', location_uuid: '', nickname: '' },
  { name: 'VeysonD', location_uuid: '', nickname: '' },
  { name: 'masuyama', location_uuid: '', nickname: '' },
  { name: 'becosuke', location_uuid: '', nickname: '' },
  { name: 'shoma', location_uuid: '', nickname: '' },
  { name: 'tarotaro0', location_uuid: '', nickname: '' },
  { name: 'yanolab', location_uuid: '', nickname: '' },
  { name: 'rerorero', location_uuid: '', nickname: '' },
  { name: 'souma', location_uuid: '', nickname: '' },
  { name: 'mando', location_uuid: '', nickname: '' },
  { name: 'tsudar', location_uuid: '', nickname: '' },
  { name: 'wadatch', location_uuid: '', nickname: '' },
  { name: 'tony', location_uuid: '', nickname: '' },
  { name: 'tenlingp', location_uuid: '', nickname: '' },
  { name: 'y-zumi', location_uuid: '', nickname: '' },
  { name: 'manas', location_uuid: '', nickname: '' },
  { name: 'junsan', location_uuid: '', nickname: '' },
  { name: 'inouet', location_uuid: '', nickname: '' },
  { name: 'shinanon', location_uuid: '', nickname: '' },
  { name: 'Mohan Bhatkar', location_uuid: '', nickname: '' },
  { name: 'Nikinsha Kesharwani', location_uuid: '', nickname: '' },
  { name: 'Kenta Shimada', location_uuid: '', nickname: '' },
  { name: 'Jayanthan Elumalai', location_uuid: '', nickname: '' },
  { name: 'Guo Yu', location_uuid: '', nickname: '' },
  { name: 'Yukanishi ', location_uuid: '', nickname: '' },
  { name: 'sasami', location_uuid: '', nickname: '' },
  { name: 'hirakiuc', location_uuid: '', nickname: '' },
  { name: 'kennyt', location_uuid: '', nickname: '' },
  { name: 'grauwoelfchen', location_uuid: '', nickname: '' },
  { name: 'jieqiong-yu', location_uuid: '', nickname: '' },
  { name: 'sen', location_uuid: '', nickname: '' },
  { name: 'Carolina', location_uuid: '', nickname: '' },
  { name: 'n_mogi', location_uuid: '', nickname: '' },
  { name: 'metafalse', location_uuid: '', nickname: '' },
  { name: 'bharath', location_uuid: '', nickname: '' },
  { name: 'codechaitu', location_uuid: '', nickname: '' },
  { name: 'nsega', location_uuid: '', nickname: '' },
  { name: 'TBH (ikasamah)', location_uuid: '', nickname: '' },
  { name: 'bprice', location_uuid: '', nickname: '' },
  { name: 'vj', location_uuid: '', nickname: '' },
  { name: 'nico', location_uuid: '', nickname: '' },
  { name: 'amit', location_uuid: '', nickname: '' },
  { name: 'kalmesh', location_uuid: '', nickname: '' },
  { name: 'CaDs', location_uuid: '', nickname: '' },
  { name: 'avalencia', location_uuid: '', nickname: '' },
  { name: 'yagi5', location_uuid: '', nickname: '' },
  { name: 'lihao.tan', location_uuid: '', nickname: '' },
  { name: 'benlei', location_uuid: '', nickname: '' },
  { name: 'shubham-kun', location_uuid: '', nickname: '' },
  { name: 'mark.hahn', location_uuid: '', nickname: '' },
  { name: 'christofer.ta', location_uuid: '', nickname: '' },
  { name: 'Martin', location_uuid: '', nickname: '' },
  { name: 'Ayman', location_uuid: '', nickname: '' },
  { name: 'audreylim', location_uuid: '', nickname: '' },
  { name: 'spencer', location_uuid: '', nickname: '' },
  { name: 'akkie', location_uuid: '', nickname: '' },
  { name: 'jd', location_uuid: '', nickname: '' },
  { name: 'daisaku', location_uuid: '', nickname: '' },
  { name: 'kimchan', location_uuid: '', nickname: '' },
  { name: 'ayeong', location_uuid: '', nickname: '' },
  { name: 'eri5', location_uuid: '', nickname: '' },
  { name: 'u-ki55', location_uuid: '', nickname: '' },
  { name: 'urahiroshi', location_uuid: '', nickname: '' },
  { name: 'mkazutaka', location_uuid: '', nickname: '' },
  { name: 'yudofu', location_uuid: '', nickname: '' },
  { name: 'kei (temporary)', location_uuid: '', nickname: '' },
  { name: 'oretama', location_uuid: '', nickname: '' },
  { name: 'tadashi', location_uuid: '', nickname: '' },
  { name: 'sota1235', location_uuid: '', nickname: '' },
  { name: 'yui_tang', location_uuid: '', nickname: '' },
  { name: 'Isoya', location_uuid: '', nickname: '' },
  { name: 'sugarshin', location_uuid: '', nickname: '' },
  { name: 'mishina', location_uuid: '', nickname: '' },
  { name: 'sanjo', location_uuid: '', nickname: '' },
  { name: 'kojima', location_uuid: '', nickname: '' },
  { name: 'chihiro', location_uuid: '', nickname: '' },
  { name: 'nekobato', location_uuid: '', nickname: '' },
  { name: 'domi', location_uuid: '', nickname: '' },
  { name: 'hatappi', location_uuid: '', nickname: '' },
  { name: 'chiu liu', location_uuid: '', nickname: '' },
  { name: 'russ', location_uuid: '', nickname: '' },
  { name: 'vwxyutarooo', location_uuid: '', nickname: '' },
  { name: 'lightnet328', location_uuid: '', nickname: '' },
  { name: 'osamu38', location_uuid: '', nickname: '' },
  { name: 'morishy', location_uuid: '', nickname: '' },
  { name: 'cantallops', location_uuid: '', nickname: '' },
  { name: 'unryu-in', location_uuid: '', nickname: '' },
  { name: 'oyakata', location_uuid: '', nickname: '' },
  { name: 'tange', location_uuid: '', nickname: '' },
  { name: 'sakata', location_uuid: '', nickname: '' },
  { name: 'chanu', location_uuid: '', nickname: '' },
  { name: 'hide', location_uuid: '', nickname: '' },
  { name: 'kurita', location_uuid: '', nickname: '' },
  { name: 'sanae', location_uuid: '', nickname: '' },
  { name: 'tak', location_uuid: '', nickname: '' },
  { name: 'katsuki', location_uuid: '', nickname: '' },
  { name: 'Taiga', location_uuid: '', nickname: '' },
  { name: 'anthony', location_uuid: '', nickname: '' },
  { name: 'hikichin', location_uuid: '', nickname: '' },
  { name: 'andy', location_uuid: '', nickname: '' },
  { name: 'yoneyama', location_uuid: '', nickname: '' },
  { name: 'mizukami', location_uuid: '', nickname: '' },
  { name: 'rkm', location_uuid: '', nickname: '' },
  { name: 'prateek', location_uuid: '', nickname: '' },
  { name: 'gyotoku2', location_uuid: '', nickname: '' },
  { name: 'deepanshu', location_uuid: '', nickname: '' },
  { name: 'gentle', location_uuid: '', nickname: '' },
  { name: 'ashish', location_uuid: '', nickname: '' },
  { name: 'karszawa', location_uuid: '', nickname: '' },
  { name: 'rkowase', location_uuid: '', nickname: '' },
  { name: 'Hiro', location_uuid: '', nickname: '' },
  { name: 'koko', location_uuid: '', nickname: '' },
  { name: 'homma(7/15~', location_uuid: '', nickname: '' },
  { name: 'Coach1', location_uuid: '', nickname: '' },
  { name: 'darek', location_uuid: '', nickname: '' },
  { name: 'jagadeesh', location_uuid: '', nickname: '' },
  { name: 'funaki', location_uuid: '', nickname: '' },
  { name: 'emma', location_uuid: '', nickname: '' },
  { name: 'joe', location_uuid: '', nickname: '' },
  { name: 'shakezo', location_uuid: '', nickname: '' },
  { name: 'antony', location_uuid: '', nickname: '' },
  { name: 'brian', location_uuid: '', nickname: '' },
  { name: 'danielg', location_uuid: '', nickname: '' },
  { name: 'too narrow to use', location_uuid: '', nickname: '' },
  { name: 'daniel', location_uuid: '', nickname: '' },
  { name: 'shun_k', location_uuid: '', nickname: '' },
  { name: 'daicche', location_uuid: '', nickname: '' },
  { name: 'matthew.gillingham', location_uuid: '', nickname: '' },
  { name: 'fujitaakk', location_uuid: '', nickname: '' },
  { name: 'mochico', location_uuid: '', nickname: '' },
  { name: 'licon', location_uuid: '', nickname: '' },
  { name: 'kirin', location_uuid: '', nickname: '' },
  { name: 'aki134', location_uuid: '', nickname: '' },
  { name: 'nana', location_uuid: '', nickname: '' },
  { name: 'maosakana', location_uuid: '', nickname: '' },
  { name: 'nakatomo', location_uuid: '', nickname: '' },
  { name: 'yuzutas0', location_uuid: '', nickname: '' },
  { name: 'pgreze', location_uuid: '', nickname: '' },
  { name: 'Coach2', location_uuid: '', nickname: '' },
  { name: 'uni0110', location_uuid: '', nickname: '' },
  { name: 'araki_atsushi', location_uuid: '', nickname: '' },
  { name: 'shoei', location_uuid: '', nickname: '' },
  { name: 'shakezo', location_uuid: '', nickname: '' },
  { name: 'Rob', location_uuid: '', nickname: '' },
  { name: 'hash', location_uuid: '', nickname: '' },
  { name: 'damian', location_uuid: '', nickname: '' },
  { name: 'masaki.haga', location_uuid: '', nickname: '' },
  { name: 'morishy', location_uuid: '', nickname: '' },
  { name: 'peter', location_uuid: '', nickname: '' },
  { name: 'paipo', location_uuid: '', nickname: '' },
  { name: 'Bruce', location_uuid: '', nickname: '' },
  { name: 'Manoj', location_uuid: '', nickname: '' },
  { name: 'yushan_ma', location_uuid: '', nickname: '' },
  { name: 'u-ki55', location_uuid: '', nickname: '' },
  { name: 'Shiuchi', location_uuid: '', nickname: '' },
  { name: 'rozen', location_uuid: '', nickname: '' },
  { name: 'yoda', location_uuid: '', nickname: '' },
  { name: 'mustafa', location_uuid: '', nickname: '' },
  { name: 'tottie', location_uuid: '', nickname: '' },
  { name: 'shizuka', location_uuid: '', nickname: '' },
  { name: 'tarunon', location_uuid: '', nickname: '' },
  { name: 'Koichi', location_uuid: '', nickname: '' },
  { name: 'natsume', location_uuid: '', nickname: '' },
  { name: 'vkgtaro', location_uuid: '', nickname: '' },
  { name: 'wataame', location_uuid: '', nickname: '' },
  { name: 's.nomiyama', location_uuid: '', nickname: '' },
  { name: 'kateinoigakukun', location_uuid: '', nickname: '' },
  { name: 'ark265', location_uuid: '', nickname: '' },
  { name: 'tajiii', location_uuid: '', nickname: '' },
  { name: 'Joshi', location_uuid: '', nickname: '' },
  { name: 'akey', location_uuid: '', nickname: '' },
  { name: 'tnk', location_uuid: '', nickname: '' },
  { name: 'khara', location_uuid: '', nickname: '' },
  { name: 'tommy', location_uuid: '', nickname: '' },
  { name: 'hisshy', location_uuid: '', nickname: '' },
  { name: 'howie.zuo', location_uuid: '', nickname: '' },
  { name: 'kitai', location_uuid: '', nickname: '' },
  { name: 'okamotti', location_uuid: '', nickname: '' },
  { name: 'kagemiku', location_uuid: '', nickname: '' },
  { name: 'Jorge', location_uuid: '', nickname: '' },
  { name: 'azuma', location_uuid: '', nickname: '' },
  { name: 'katsura', location_uuid: '', nickname: '' },
  { name: 'ryo_sen', location_uuid: '', nickname: '' },
  { name: 'rikayun', location_uuid: '', nickname: '' },
  { name: 'yoshi', location_uuid: '', nickname: '' },
  { name: 'iov', location_uuid: '', nickname: '' },
  { name: 'fuji', location_uuid: '', nickname: '' },
  { name: 'mattsun', location_uuid: '', nickname: '' },
  { name: 'kotazi', location_uuid: '', nickname: '' },
  { name: 'u_gene', location_uuid: '', nickname: '' },
  { name: 'mootoh', location_uuid: '', nickname: '' },
  { name: 'igachan', location_uuid: '', nickname: '' },
  { name: 'ake', location_uuid: '', nickname: '' },
  { name: 'charlie', location_uuid: '', nickname: '' },
  { name: 'yytnk', location_uuid: '', nickname: '' },
  { name: 'danieltill', location_uuid: '', nickname: '' },
  { name: 'shutoiiyama', location_uuid: '', nickname: '' },
  { name: 'shundai', location_uuid: '', nickname: '' },
  { name: 'anboo', location_uuid: '', nickname: '' },
  { name: 'gakkie', location_uuid: '', nickname: '' },
  { name: 'sintario', location_uuid: '', nickname: '' },
  { name: 'tim', location_uuid: '', nickname: '' },
  { name: 'pakupark', location_uuid: '', nickname: '' },
  { name: 'nattsu', location_uuid: '', nickname: '' },
  { name: 'k.ohashi', location_uuid: '', nickname: '' },
  { name: 'aki', location_uuid: '', nickname: '' },
  { name: 'yilin', location_uuid: '', nickname: '' },
  { name: 'tiffany', location_uuid: '', nickname: '' },
  { name: 'nurse_akdl', location_uuid: '', nickname: '' },
  { name: 'hiza', location_uuid: '', nickname: '' },
  { name: 'sakata2', location_uuid: '', nickname: '' },
  { name: 'carlos', location_uuid: '', nickname: '' },
  { name: 'Mytt', location_uuid: '', nickname: '' },
  { name: 'karin', location_uuid: '', nickname: '' },
  { name: 'allan.conda', location_uuid: '', nickname: '' },
  { name: 'okb', location_uuid: '', nickname: '' },
  { name: 'yuzuna', location_uuid: '', nickname: '' },
  { name: 'sottar', location_uuid: '', nickname: '' },
  { name: 'arvin', location_uuid: '', nickname: '' },
  { name: 'motokiee', location_uuid: '', nickname: '' },
  { name: 'thelastjedi', location_uuid: '', nickname: '' },
  { name: 'ucchi_naotaka1128', location_uuid: '', nickname: '' },
  { name: 'whatasoda', location_uuid: '', nickname: '' },
  { name: 'Runa', location_uuid: '', nickname: '' },
  { name: 'shiroma', location_uuid: '', nickname: '' },
  { name: 'nammy', location_uuid: '', nickname: '' },
  { name: 'tennis', location_uuid: '', nickname: '' },
  { name: 'taiyo', location_uuid: '', nickname: '' },
  { name: 'QA', location_uuid: '', nickname: '' },
  { name: 'stinge', location_uuid: '', nickname: '' },
  { name: 'chan-kuma', location_uuid: '', nickname: '' },
  { name: 'ota', location_uuid: '', nickname: '' },
  { name: 'ogawa', location_uuid: '', nickname: '' },
  { name: 'shishamo', location_uuid: '', nickname: '' },
  { name: 'jeff', location_uuid: '', nickname: '' },
  { name: 'kojun', location_uuid: '', nickname: '' },
  { name: 'akagawa', location_uuid: '', nickname: '' },
  { name: 'misupuri', location_uuid: '', nickname: '' },
  { name: 'naocchi (Finance)', location_uuid: '', nickname: '' },
  { name: 'protosdhk', location_uuid: '', nickname: '' },
  { name: 'tomiken', location_uuid: '', nickname: '' },
  { name: 'Newcomer', location_uuid: '', nickname: '' },
  { name: 'Newcomer', location_uuid: '', nickname: '' },
  { name: 'murata', location_uuid: '', nickname: '' },
  { name: 'yoshiko (Finance)', location_uuid: '', nickname: '' },
  { name: 'yoshikawa', location_uuid: '', nickname: '' },
  { name: 'asaocar', location_uuid: '', nickname: '' },
  { name: 'ayaka', location_uuid: '', nickname: '' },
  { name: 'naomi', location_uuid: '', nickname: '' },
  { name: 'kaz', location_uuid: '', nickname: '' },
  { name: 'hijikata（マーケ）', location_uuid: '', nickname: '' },
  { name: 'Carolina', location_uuid: '', nickname: '' },
  { name: 'ragen', location_uuid: '', nickname: '' },
  { name: 'shiwa_akane', location_uuid: '', nickname: '' },
  { name: 'nagasako', location_uuid: '', nickname: '' },
  { name: 'Hoshi', location_uuid: '', nickname: '' },
  { name: 'peipei (Finance)', location_uuid: '', nickname: '' },
  { name: 'konatsu', location_uuid: '', nickname: '' },
  { name: 'karubi', location_uuid: '', nickname: '' },
  { name: 'han', location_uuid: '', nickname: '' },
  { name: 'kinkin', location_uuid: '', nickname: '' },
  { name: 'todamai', location_uuid: '', nickname: '' },
  { name: 'mj (Finance)', location_uuid: '', nickname: '' },
  { name: 'Riana', location_uuid: '', nickname: '' },
  { name: 'aoimo', location_uuid: '', nickname: '' },
  { name: 'Ash', location_uuid: '', nickname: '' },
  { name: 'nami', location_uuid: '', nickname: '' },
  { name: 'Nambo', location_uuid: '', nickname: '' },
  { name: 'shusuke', location_uuid: '', nickname: '' },
  { name: 'satomi', location_uuid: '', nickname: '' },
  { name: 'pikari', location_uuid: '', nickname: '' },
  { name: 'Nokazu', location_uuid: '', nickname: '' },
  { name: 'yu.ishikawa', location_uuid: '', nickname: '' },
  { name: 'Nakato', location_uuid: '', nickname: '' },
  { name: 'emori', location_uuid: '', nickname: '' },
  { name: 'NJ', location_uuid: '', nickname: '' },
  { name: 'cont-tso(10/1〜12/31）', location_uuid: '', nickname: '' },
  { name: 'Magome', location_uuid: '', nickname: '' },
  { name: 'Kondo', location_uuid: '', nickname: '' },
  { name: 'cont-tyoshikuni(9/2〜11/30）', location_uuid: '', nickname: '' },
  { name: 'hisahiko', location_uuid: '', nickname: '' },
  { name: 'sadah', location_uuid: '', nickname: '' },
  { name: 'tweeeety', location_uuid: '', nickname: '' },
  { name: 'naoto', location_uuid: '', nickname: '' },
  { name: 'yamatoy', location_uuid: '', nickname: '' },
  { name: 'sakiccho', location_uuid: '', nickname: '' },
  { name: 'louna', location_uuid: '', nickname: '' },
  { name: 'abhi', location_uuid: '', nickname: '' },
  { name: 'yukki-ohdo', location_uuid: '', nickname: '' },
  { name: 'seino', location_uuid: '', nickname: '' },
  { name: 'uemu', location_uuid: '', nickname: '' },
  { name: 'masudak', location_uuid: '', nickname: '' },
  { name: 'mmiy', location_uuid: '', nickname: '' },
  { name: 'jolly', location_uuid: '', nickname: '' },
  { name: 'ichimayu', location_uuid: '', nickname: '' },
  { name: 'kk', location_uuid: '', nickname: '' },
  { name: 'harajune', location_uuid: '', nickname: '' },
  { name: 'kayoreena', location_uuid: '', nickname: '' },
  { name: 'yuki.t', location_uuid: '', nickname: '' },
  { name: 'suguru', location_uuid: '', nickname: '' },
  { name: 'maki', location_uuid: '', nickname: '' },
  { name: 'miccha', location_uuid: '', nickname: '' },
  { name: 'jatin', location_uuid: '', nickname: '' },
  { name: 'inaba', location_uuid: '', nickname: '' },
  { name: 'Jon', location_uuid: '', nickname: '' },
  { name: 'afroscript', location_uuid: '', nickname: '' },
  { name: 'futoshi', location_uuid: '', nickname: '' },
  { name: 'tomocomoco(業)', location_uuid: '', nickname: '' },
  { name: 'hirona', location_uuid: '', nickname: '' },
  { name: 'jackie', location_uuid: '', nickname: '' },
  { name: 'asai', location_uuid: '', nickname: '' },
  { name: 'Tuttiq', location_uuid: '', nickname: '' },
  { name: 'braitom', location_uuid: '', nickname: '' },
  { name: 'kwakasa', location_uuid: '', nickname: '' },
  { name: 'kiko', location_uuid: '', nickname: '' },
  { name: 'danielsilva', location_uuid: '', nickname: '' },
  { name: 'kubokkie', location_uuid: '', nickname: '' },
  { name: 'shibuchin', location_uuid: '', nickname: '' },
  { name: 'Aki', location_uuid: '', nickname: '' },
  { name: 'maho', location_uuid: '', nickname: '' },
  { name: 'jess', location_uuid: '', nickname: '' },
  { name: 'hepako', location_uuid: '', nickname: '' },
  { name: 'Tamo-san', location_uuid: '', nickname: '' },
  { name: 'jess', location_uuid: '', nickname: '' },
  { name: 'tatsuo', location_uuid: '', nickname: '' },
  { name: 'kei_hase', location_uuid: '', nickname: '' },
  { name: 'yoko.sasaki', location_uuid: '', nickname: '' },
  { name: 'shakky', location_uuid: '', nickname: '' },
  { name: 'Lei', location_uuid: '', nickname: '' },
  { name: 'KB', location_uuid: '', nickname: '' },
  { name: 'mikako', location_uuid: '', nickname: '' },
  { name: 'tomobe', location_uuid: '', nickname: '' },
  { name: 'kinoko', location_uuid: '', nickname: '' },
  { name: 'tomochin', location_uuid: '', nickname: '' },
  { name: 'jun', location_uuid: '', nickname: '' },
  { name: 'liz', location_uuid: '', nickname: '' },
  { name: 'massuu', location_uuid: '', nickname: '' },
  { name: 'mkanno', location_uuid: '', nickname: '' },
  { name: 'takaya', location_uuid: '', nickname: '' },
  { name: 'mayun', location_uuid: '', nickname: '' },
  { name: 'tomoya.o', location_uuid: '', nickname: '' },
  { name: 'mirai', location_uuid: '', nickname: '' },
  { name: 'mirai', location_uuid: '', nickname: '' },
  { name: 'mirai', location_uuid: '', nickname: '' },
  { name: 'matsunaga', location_uuid: '', nickname: '' },
  { name: 'nagai', location_uuid: '', nickname: '' },
  { name: 'egami', location_uuid: '', nickname: '' },
  { name: 'miyama', location_uuid: '', nickname: '' },
  { name: 'sato', location_uuid: '', nickname: '' },
  { name: 'kasahara', location_uuid: '', nickname: '' },
  { name: 'okano', location_uuid: '', nickname: '' },
  { name: 'marony', location_uuid: '', nickname: '' },
  { name: 'kikuchi', location_uuid: '', nickname: '' },
  { name: 'vic', location_uuid: '', nickname: '' },
  { name: 'yossy', location_uuid: '', nickname: '' },
  { name: 'kiyokawa', location_uuid: '', nickname: '' },
  { name: 'a-den', location_uuid: '', nickname: '' },
  { name: 'hasegawa', location_uuid: '', nickname: '' },
  { name: 'narita', location_uuid: '', nickname: '' },
  { name: 'mugi', location_uuid: '', nickname: '' },
  { name: 'amico', location_uuid: '', nickname: '' },
  { name: 'osushi', location_uuid: '', nickname: '' },
  { name: 'helosshi', location_uuid: '', nickname: '' },
  { name: 'ikegami', location_uuid: '', nickname: '' },
  { name: 'tmp', location_uuid: '', nickname: '' },
  { name: 'michelle', location_uuid: '', nickname: '' },
  { name: 'megmeg', location_uuid: '', nickname: '' },
  { name: 'shu', location_uuid: '', nickname: '' },
  { name: 'demirhan', location_uuid: '', nickname: '' },
  { name: 'hids', location_uuid: '', nickname: '' },
  { name: 'mizhrtn', location_uuid: '', nickname: '' },
  { name: 'asawo', location_uuid: '', nickname: '' },
  { name: 'alex', location_uuid: '', nickname: '' },
  { name: 'Spare/Maya', location_uuid: '', nickname: '' },
  { name: 'Juan', location_uuid: '', nickname: '' },
  { name: 'Diallo', location_uuid: '', nickname: '' },
  { name: 'emma', location_uuid: '', nickname: '' },
  { name: 'arminmin ', location_uuid: '', nickname: '' },
  { name: 'ehab', location_uuid: '', nickname: '' },
  { name: 'wataruhh', location_uuid: '', nickname: '' },
  { name: 'kazama', location_uuid: '', nickname: '' },
  { name: 'tomoito', location_uuid: '', nickname: '' },
  { name: 'nemoto', location_uuid: '', nickname: '' },
  { name: 'kodai', location_uuid: '', nickname: '' },
  { name: 'fumiharu', location_uuid: '', nickname: '' },
  { name: 'hkondo134', location_uuid: '', nickname: '' },
  { name: 'wam', location_uuid: '', nickname: '' },
  { name: 'kikki', location_uuid: '', nickname: '' },
  { name: 'kengo', location_uuid: '', nickname: '' },
  { name: 'haruna', location_uuid: '', nickname: '' },
  { name: 'yuka', location_uuid: '', nickname: '' },
  { name: 'takeyama', location_uuid: '', nickname: '' },
  { name: 'hiroto_fujimura', location_uuid: '', nickname: '' },
  { name: 'shu', location_uuid: '', nickname: '' },
  { name: 'takumi', location_uuid: '', nickname: '' },
  { name: 'deto', location_uuid: '', nickname: '' },
  { name: 'kazy', location_uuid: '', nickname: '' },
  { name: 'hirano', location_uuid: '', nickname: '' },
  { name: 'oonogi', location_uuid: '', nickname: '' },
  { name: 'Azeem', location_uuid: '', nickname: '' },
  { name: 'Jason', location_uuid: '', nickname: '' },
  { name: 'Lionetti', location_uuid: '', nickname: '' },
  { name: 'Yann', location_uuid: '', nickname: '' },
  { name: 'Thiago', location_uuid: '', nickname: '' },
  { name: 'Su Gi', location_uuid: '', nickname: '' },
  { name: 'Suezawa', location_uuid: '', nickname: '' },
  { name: 'David', location_uuid: '', nickname: '' },
  { name: 'Simon', location_uuid: '', nickname: '' },
  { name: 'yam86', location_uuid: '', nickname: '' },
  { name: 'kuu', location_uuid: '', nickname: '' },
  { name: 'kaito', location_uuid: '', nickname: '' },
  { name: 'yoichi', location_uuid: '', nickname: '' },
  { name: 'rhomel', location_uuid: '', nickname: '' },
  { name: 'neri', location_uuid: '', nickname: '' },
  { name: 'Danji', location_uuid: '', nickname: '' },
  { name: 'Jeff', location_uuid: '', nickname: '' },
  { name: 'Kazuma', location_uuid: '', nickname: '' },
  { name: 'chris', location_uuid: '', nickname: '' },
  { name: 'darren', location_uuid: '', nickname: '' },
  { name: 'Yamaki', location_uuid: '', nickname: '' },
  { name: 'Mizuki', location_uuid: '', nickname: '' },
  { name: 'Hiderer', location_uuid: '', nickname: '' },
  { name: 'shu', location_uuid: '', nickname: '' },
  { name: 'ryan', location_uuid: '', nickname: '' },
  { name: 'hurutoriya', location_uuid: '', nickname: '' },
  { name: 'shido', location_uuid: '', nickname: '' },
  { name: 'Yilin Li', location_uuid: '', nickname: '' },
  { name: 'Akihiro Shimizu', location_uuid: '', nickname: '' },
  { name: 'Arao Kengo', location_uuid: '', nickname: '' },
  { name: 'Ni', location_uuid: '', nickname: '' },
  { name: 'Toby', location_uuid: '', nickname: '' },
  { name: 'Arnold', location_uuid: '', nickname: '' },
  { name: 'deepak', location_uuid: '', nickname: '' },
  { name: 'pablo', location_uuid: '', nickname: '' },
  { name: 'yoshi.s', location_uuid: '', nickname: '' },
  { name: 'kimuras', location_uuid: '', nickname: '' },
  { name: 'abhishek', location_uuid: '', nickname: '' },
  { name: 'sugan', location_uuid: '', nickname: '' },
  { name: 'sandeep', location_uuid: '', nickname: '' },
  { name: 'k-raj', location_uuid: '', nickname: '' },
  { name: 'Antony Lam', location_uuid: '', nickname: '' },
  { name: 'aman', location_uuid: '', nickname: '' },
  { name: 'subodh', location_uuid: '', nickname: '' },
  { name: 'adam', location_uuid: '', nickname: '' },
  { name: 'cournape', location_uuid: '', nickname: '' },
  { name: 'takazawa', location_uuid: '', nickname: '' },
  { name: 'Yuanqin Lu', location_uuid: '', nickname: '' },
  { name: 'Kosuke Arase', location_uuid: '', nickname: '' },
  { name: 'mzk', location_uuid: '', nickname: '' },
  { name: 'mrkm', location_uuid: '', nickname: '' },
  { name: 'ynqa', location_uuid: '', nickname: '' },
  { name: 'shopetan', location_uuid: '', nickname: '' },
  { name: 'kamino', location_uuid: '', nickname: '' },
  { name: 'abhinav', location_uuid: '', nickname: '' },
  { name: 'shibui', location_uuid: '', nickname: '' },
  { name: 'oshima', location_uuid: '', nickname: '' },
  { name: 'kumu', location_uuid: '', nickname: '' },
  { name: 'wakanapo', location_uuid: '', nickname: '' },
  { name: 'metalunk', location_uuid: '', nickname: '' },
  { name: 'mookjp', location_uuid: '', nickname: '' },
  { name: 'varun(7/1~7/31)', location_uuid: '', nickname: '' },
  { name: 'Anukul', location_uuid: '', nickname: '' },
  { name: 'johnny_oqrusk', location_uuid: '', nickname: '' },
  { name: 'hnakagawa', location_uuid: '', nickname: '' },
  { name: 'kumazawa', location_uuid: '', nickname: '' },
  { name: 'PrashantMaurya', location_uuid: '', nickname: '' },
  { name: 'Greg', location_uuid: '', nickname: '' },
  { name: '(TEMP)johnny_oqrusk', location_uuid: '', nickname: '' },
  { name: 'takata', location_uuid: '', nickname: '' },
  { name: 'sohara', location_uuid: '', nickname: '' },
  { name: 'uchiyama', location_uuid: '', nickname: '' },
  { name: 'tairosan', location_uuid: '', nickname: '' },
  { name: 'yuu', location_uuid: '', nickname: '' },
  { name: 'wada', location_uuid: '', nickname: '' },
  { name: 'AJ 8/1~', location_uuid: '', nickname: '' },
  { name: 'Conner 9/1 ~', location_uuid: '', nickname: '' },
  { name: 'furusawa', location_uuid: '', nickname: '' },
  { name: 'masarz', location_uuid: '', nickname: '' },
  { name: 'drew 8/16~', location_uuid: '', nickname: '' },
  { name: 'tsudar', location_uuid: '', nickname: '' },
  { name: 'Junpei Nishimoto', location_uuid: '', nickname: '' },
  { name: 'Minoru Osuka', location_uuid: '', nickname: '' },
  { name: 'Yanpeng Lin', location_uuid: '', nickname: '' },
  { name: 'Aman Jain', location_uuid: '', nickname: '' },
  { name: 'Marne Prasad', location_uuid: '', nickname: '' },
  { name: 'Jithin Sukumar', location_uuid: '', nickname: '' },
  { name: 'Riku Togashi', location_uuid: '', nickname: '' },
  { name: 'Akira Ishino', location_uuid: '', nickname: '' },
  { name: 'Kei Yagi', location_uuid: '', nickname: '' },
  { name: 'Kazuaki Hiraga', location_uuid: '', nickname: '' },
  { name: 'Reggie Lai', location_uuid: '', nickname: '' },
  { name: 'Takuya Asano (9/1~', location_uuid: '', nickname: '' },
  { name: 'y-tajiri', location_uuid: '', nickname: '' },
  { name: 'keizo042', location_uuid: '', nickname: '' },
  { name: 'Sugaya', location_uuid: '', nickname: '' },
  { name: 'lain', location_uuid: '', nickname: '' },
  { name: 'maruyama', location_uuid: '', nickname: '' },
  { name: 'crcrpr', location_uuid: '', nickname: '' },
  { name: 'sugiki', location_uuid: '', nickname: '' },
  { name: 'cno', location_uuid: '', nickname: '' },
  { name: 'Riley', location_uuid: '', nickname: '' },
  { name: 'JohnVS', location_uuid: '', nickname: '' },
  { name: 'David', location_uuid: '', nickname: '' },
  { name: 'Marc Anderson', location_uuid: '', nickname: '' },
  { name: 'Maz', location_uuid: '', nickname: '' },
  { name: 'Asako', location_uuid: '', nickname: '' },
  { name: 'Mayuko', location_uuid: '', nickname: '' },
  { name: 'Hirona', location_uuid: '', nickname: '' },
];
